name: Reusable Workflow
on: 
  workflow_call:
    inputs: 
      greeting_var: 
        description: Used in echo statement
        required: true
        type: string
        default: "Hello"
    secrets:
      some_secret: 
        required: true
jobs:
  Reusable_workflow_test :
    runs-on: ubuntu-latest 
    steps:
      - name: Confirm Message
        run: |
          echo "I am in reusable workflow"
      - name: Input var display
        run: |
          echo " ${{ inputs.greeting_var}}"
      - name: secret fetching
        run: |
          echo "My little secret ${{secrets.some_secret}}
