name: Reusable Workflow
on: 
  workflow_call:
    inputs: 
      greeting_var: 
        description: Used in echo statement
        required: true
        type: string
        default: "Hello"
    secrets:
      some_secret: 
        required: true
    outputs:
      combined_op: 
        description: Output combined here
        value: ${{ jobs.Reusable_workflow_test.outputs.statement }}
    
jobs:
  Reusable_workflow_test :
    runs-on: ubuntu-latest 
    outputs:
      statement: ${{ steps.op_val.outputs.combined_op }}
    steps:
      - name: Confirm Message
        run: |
          echo "I am in reusable workflow"
      - name: Input var display
        run: |
          echo " ${{ inputs.greeting_var}}"
      - name: secret fetching
        run: |
          echo "My little secret ${{secrets.some_secret}}"
      - name: Send the output
        id: op_val
        run: |
          echo "combined_op=success" >> $GITHUB_OUTPUT
