name: Testing reusable workflow 
on: push
jobs:
  reusable_wf_test:
    uses: ./.github/workflows/reusable_wf.yaml
    with:
      greeting_var: "Namaste, Hi"
    secrets:
      some_secret: ${{ secrets.ACCESS_KEY_ID}}
  op_fetch:
    runs-on: ubuntu-latest 
    needs: reusable_wf_test
    steps:
      - name: fetch output
        run: |
          echo "${{ needs.reusable_wf_test.outputs.combined_op}}"
    
    
     
      
